<?php
// Set the timezone
date_default_timezone_set('Asia/Singapore');
session_start();

// Check if user is logged in and is a patient
if (isset($_SESSION["user"])) {
    if (($_SESSION["user"]) == "" || $_SESSION['usertype'] != 'p') {
        header("location: login.php");
        exit;
    }
} else {
    header("location: ../login.php");
    exit;
}

// Include database connection
include("../connection.php");

// Get the email parameter and validate it
if (!isset($_GET['email']) || $_GET['email'] !== $_SESSION["user"]) {
    // Security check: Only allow users to download their own records
    header("Location: profile.php");
    exit;
}

$useremail = $_GET['email'];
$userrow = $database->query("SELECT * FROM patient WHERE pemail='$useremail'");
$userfetch = $userrow->fetch_assoc();
$userid = $userfetch["pid"];
$username = $userfetch["pname"];

// Get medical history data
$medicalData = $database->query("SELECT * FROM medical_history WHERE email = '$useremail'");
$hasMedicalHistory = $medicalData->num_rows > 0;

if (!$hasMedicalHistory) {
    // If no medical history, redirect back to profile
    header("Location: profile.php");
    exit;
}

$medical = $medicalData->fetch_assoc();

// Include TCPDF library
require_once('../tcpdf/tcpdf.php');

// Create new PDF document
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('ToothTrackr Dental System');
$pdf->SetAuthor('ToothTrackr Dental Clinic');
$pdf->SetTitle('Official Medical Record - ' . $username);
$pdf->SetSubject('Medical Record');

// Set document header
class MYPDF extends TCPDF {
    // Page header
    public function Header() {
        // Logo
        $image_file = '../assets/img/logo.png'; // Change to your logo path
        if (file_exists($image_file)) {
            $this->Image($image_file, 15, 10, 25, '', 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        }
        // Set font
        $this->SetFont('helvetica', 'B', 12);
        // Title
        $this->Cell(0, 15, 'Songco Dental and Medical Clinic', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        // Line break
        $this->Ln(10);
        // Thin line
        $this->Line(15, 30, 195, 30, array('width' => 0.2));
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number and copyright
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages().' | Confidential Medical Document - Generated by ToothTrackr Dental System on '.date('d/m/Y'), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(15, 35, 15);
$pdf->SetHeaderMargin(20);
$pdf->SetFooterMargin(15);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 25);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Set font
$pdf->SetFont('helvetica', '', 10);

// Add a page
$pdf->AddPage();

// Create the medical record content with official styling
$html = '
<style>
    .header {
        font-size: 14pt;
        text-align: center;
        font-weight: bold;
        margin-bottom: 10px;
    }
    .subheader {
        font-size: 10pt;
        text-align: center;
        margin-bottom: 15px;
        color: #555555;
    }
    .section-title {
        font-size: 11pt;
        font-weight: bold;
        background-color: #f0f0f0;
        padding: 5px;
        border-left: 4px solid #2b4c7e;
        margin: 10px 0 5px 0;
    }
    .field-group {
        margin-bottom: 8px;
    }
    .field-label {
        font-weight: bold;
        width: 60mm;
        display: inline-block;
    }
    .field-value {
        display: inline-block;
    }
    .signature-area {
        margin-top: 30px;
    }
    .signature-line {
        border-top: 1px solid #000000;
        width: 70mm;
        margin-top: 20px;
    }
    .signature-label {
        font-size: 9pt;
        text-align: center;
    }
    .official-stamp {
        text-align: right;
        margin-top: 30px;
        font-style: italic;
        color: #777777;
    }
    .bordered-cell {
        border: 1px solid #dddddd;
        padding: 5px;
    }
    .full-width {
        width: 100%;
        border-collapse: collapse;
    }
    .vertical-space {
        height: 10mm;
    }
</style>

<div class="header">PATIENT MEDICAL HISTORY</div>
<div class="subheader">ToothTrackr | Confidential Patient Document</div>

<div class="section-title">PATIENT INFORMATION</div>
<BR>
<table class="full-width">
    <tr>
        <td class="bordered-cell" width="50%"><span class="field-label">Patient Name:</span> ' . htmlspecialchars($username) . '</td>
        <td class="bordered-cell" width="25%"><span class="field-label">Patient ID:</span> ' . htmlspecialchars($userid) . '</td>
        <td class="bordered-cell" width="25%"><span class="field-label">Date:</span> ' . date('d/m/Y') . '</td>
    </tr>
    <tr>
        <td class="bordered-cell"><span class="field-label">Date of Birth:</span> ' . htmlspecialchars($userfetch['pdob']) . '</td>
        <td class="bordered-cell"><span class="field-label">Gender:</span> ' . (isset($userfetch['pgender']) ? htmlspecialchars($userfetch['pgender']) : 'Not specified') . '</td>
        <td class="bordered-cell"><span class="field-label">Phone:</span> ' . htmlspecialchars($userfetch['ptel']) . '</td>
    </tr>
    <tr>
        <td class="bordered-cell" colspan="3"><span class="field-label">Address:</span> ' . htmlspecialchars($userfetch['paddress']) . '</td>
    </tr>
</table>
<BR>
<div class="section-title">MEDICAL HISTORY</div>
<table class="full-width">
    <tr>
        <td class="bordered-cell" width="50%">
            <div class="field-group"><span class="field-label">General Health Status:</span> ' . htmlspecialchars($medical['good_health']) . '</div>
            <div class="field-group"><span class="field-label">Under Medical Treatment:</span> ' . htmlspecialchars($medical['under_treatment']) . '</div>
            <div class="field-group"><span class="field-label">Serious Illness/Surgery:</span> ' . htmlspecialchars($medical['serious_illness']) . '</div>
        </td>
        <td class="bordered-cell" width="50%">
            <div class="field-group"><span class="field-label">Hospitalized:</span> ' . htmlspecialchars($medical['hospitalized']) . '</div>
            <div class="field-group"><span class="field-label">Current Medications:</span> ' . htmlspecialchars($medical['medication']) . '</div>
            <div class="field-group"><span class="field-label">Tobacco Use:</span> ' . htmlspecialchars($medical['tobacco']) . '</div>
        </td>
    </tr>
    <tr>
        <td class="bordered-cell" colspan="2">
            <div class="field-group"><span class="field-label">Known Allergies:</span> ' . (!empty($medical['allergies']) ? htmlspecialchars($medical['allergies']) : 'None reported') . '</div>
        </td>
    </tr>
    <tr>
        <td class="bordered-cell" colspan="2">
            <div class="field-group"><span class="field-label">Existing Health Conditions:</span> ' . (!empty($medical['health_conditions']) ? htmlspecialchars($medical['health_conditions']) : 'None reported') . '</div>
        </td>
    </tr>
</table>
<BR>
<div class="section-title">DENTAL HEALTH INFORMATION</div>
<table class="full-width">
    <tr>
        <td class="bordered-cell" width="50%">
            <div class="field-group"><span class="field-label">Bleeding Time Issues:</span> ' . (!empty($medical['bleeding_time']) ? htmlspecialchars($medical['bleeding_time']) : 'None reported') . '</div>
            <div class="field-group"><span class="field-label">Blood Pressure Issues:</span> ' . (!empty($medical['blood_pressure']) ? htmlspecialchars($medical['blood_pressure']) : 'Normal') . '</div>
        </td>
        <td class="bordered-cell" width="50%">
            <div class="field-group"><span class="field-label">Drug Use:</span> ' . htmlspecialchars($medical['drugs']) . '</div>
            <div class="field-group"><span class="field-label">Last Dental Visit:</span> ' . (!empty($medical['last_dental_visit']) ? htmlspecialchars($medical['last_dental_visit']) : 'Not specified') . '</div>
        </td>
    </tr>
</table>

<div class="vertical-space"></div>

<div class="section-title">CERTIFICATION</div>
<br><br><br><br>
<table class="full-width">
    <tr>
        <td width="33%">
            <div class="signature-line"></div>
            <div class="signature-label">Patient Signature</div>
        </td>
        <td width="33%">
            <div class="signature-line"></div>
            <div class="signature-label">Dentist Signature</div>
        </td>
        <td width="33%">
            <div class="signature-line"></div>
            <div class="signature-label">Date</div>
        </td>
    </tr>
</table>

<div class="official-stamp">
    <i>This document is valid only with official clinic stamp and signature</i>
</div>
';

// Print HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('Medical_Record_' . $userid . '_' . date('Ymd') . '.pdf', 'D');
exit;
?>